### ISSUE TITLE
Bug: Timestamp in the notification message should be in UTC time zone

### ISSUE THREAD

**Issue by rish691** [hypertrace/hypertrace-alert-engine#32]
Currently the time stamp seems to be in IST 

Reference issue: https://github.com/hypertrace/hypertrace-alert-engine/pull/20

**Comment by sarthak77** [comment]
_tl;dr_
There is an inbuilt setting in slack that automatically converts the time into local timezone. 
<hr>

While debugging the issue we found that that timestamp in notification is always in _IST_ despite it being set in the _UTC_ format. So depending on the timezone of the person, the _epochSeconds_ would automatically get converted into local timezone. This local timezone may come from the timezone set in their slack or from their local timezone set in their laptop. In our case the timezone was being extracted from the local timezone set in mac and thus this issue was persisting even after changing the timezone in notification message and in slack.

References:

- [Date formatting in slack](https://api.slack.com/reference/surfaces/formatting)
- [Slack block kit builder](https://app.slack.com/block-kit-builder/TDUFP6GBS#%7B%22attachments%22:%5B%7B%22blocks%22:%5B%5D%7D%5D%7D)
